apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: tsunami-security-scanner
  labels:
    app.kubernetes.io/name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
    spec:
      initContainers:
      - name: download-tools
        image: alpine:3.8
        command: [sh, -c]
        args:
        - {{ .Values.payload }}
      containers:
      - name: nginx
        image: nginx:latest
        ports:
          - name: http
            containerPort: 80
